version: "3.9"

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  daily:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4001:4000
    environment:
      MIX_ENV: prod
      DATABASE_URL: postgres://postgres:postgres@postgres/daily_prod
      SECRET_KEY_BASE: RoWIz8MJ0e7vMI9anXkEExGDc2LzOkaF1iByudrJtyRVJz3hDrFnNveUmvf/2Ijv
      PHX_HOST: localhost
      PHX_URL_PORT: '4001'
      PHX_URL_SCHEME: 'http'
      WEATHER_SERVICE_URL: 'http://weather:5000'
    command: >
      sh -c "mix setup &&
             mix phx.server"
    working_dir: /app
    volumes:
      - ./config:/app/config:ro
      - ./lib:/app/lib:ro
      - ./priv:/app/priv:ro
      - ./mix.exs:/app/mix.exs:ro
      - ./mix.lock:/app/mix.lock:rw
      - elixir-deps:/app/deps/
      - elixir-build:/app/_build/
    logging:
      driver: loki
      options:
        loki-url: 'http://loki:loki@localhost:3100/loki/api/v1/push'

  caddy:
    image: caddy:2.5.1-alpine
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 4002:4002
    environment:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://tempo:4317"
      OTEL_SERVICE_NAME: "caddy"
    logging:
      driver: loki
      options:
        loki-url: 'http://loki:loki@localhost:3100/loki/api/v1/push'

  weather:
    image: caddy:2.5.1-alpine
    volumes:
      - ./docker/weather/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 5000:5000
    environment:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://tempo:4317"
      OTEL_SERVICE_NAME: "weather"
    logging:
      driver: loki
      options:
        loki-url: 'http://loki:loki@localhost:3100/loki/api/v1/push'

  # Observability Tools
  loki:
    image: grafana/loki:2.5.0
    volumes:
      - ./docker/loki/loki-config.yml:/etc/loki/loki-config.yml
      - loki-data-index:/loki-index
      - loki-data-chunks:/loki-chunks
    expose:
      - 3100
    ports:
      - '3100:3100'
    command: '-config.file=/etc/loki/loki-config.yml'

  grafana:
    image: grafana/grafana:8.5.4
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/:/etc/grafana/provisioning/
    logging:
      driver: loki
      options:
        loki-url: 'http://loki:loki@localhost:3100/loki/api/v1/push'
  prometheus:
    image: prom/prometheus:v2.36.0
    volumes:
      - ./docker/prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    logging:
      driver: loki
      options:
        loki-url: 'http://loki:loki@localhost:3100/loki/api/v1/push'
  tempo:
    image: grafana/tempo:1.4.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    logging:
      driver: loki
      options:
        loki-url: 'http://loki:loki@localhost:3100/loki/api/v1/push'
volumes:
  elixir-deps: {}
  elixir-build: {}
  postgres_data: {}
  loki-data-index: {}
  loki-data-chunks: {}
  grafana-data: {}
  prometheus-data: {}
  tempo-data: {}