# config file version
apiVersion: 1

datasources:
  - uid: loki
    name: loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '[tT][rR][aA][cC][eE][._-]?[iI][dD][=":]+([a-z0-9]+)'
          name: traceID
          url: '$${__value.raw}'
    editable: false
  - uid: prometheus
    name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: false
  - uid: tempo
    name: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200