# config file version
apiVersion: 1

datasources:
  - uid: loki
    name: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
  - uid: prometheus
    name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: false
  - uid: tempo
    name: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200