# config file version
apiVersion: 1

datasources:
  - name: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: false